name: Build, test and upload the module

on: [push, check_run]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        version:
          - 5.13.2
        platform:
          - gcc_64
          - android_arm64_v8a
          - android_x86_64
          - android_armv7
          - android_x86
          - wasm_32
          - msvc2017_64
          - msvc2017
          - winrt_x64_msvc2017
          - winrt_x86_msvc2017
          - winrt_armv7_msvc2017
          - mingw73_64
          - mingw73_32
          - clang_64
          - ios

        include:
          - platform: gcc_64
            os: ubuntu-latest
            cachebase: /opt/hostedtoolcache
            test: true
            examples: true
            doc: true
            testflags: "-j 1"
          - platform: android_arm64_v8a
            os: ubuntu-latest
            cachebase: /opt/hostedtoolcache
            test: false
            examples: false
            doc: false
            testflags: "-j 1"
          - platform: android_x86_64
            os: ubuntu-latest
            cachebase: /opt/hostedtoolcache
            test: false
            examples: false
            doc: false
            testflags: "-j 1"
          - platform: android_armv7
            os: ubuntu-latest
            cachebase: /opt/hostedtoolcache
            test: false
            examples: false
            doc: false
            testflags: "-j 1"
          - platform: android_x86
            os: ubuntu-latest
            cachebase: /opt/hostedtoolcache
            test: false
            examples: false
            doc: false
            testflags: "-j 1"
          - platform: wasm_32
            os: ubuntu-latest
            cachebase: /opt/hostedtoolcache
            test: false
            examples: false
            doc: false
            testflags: "-j 1"
          - platform: msvc2017_64
            os: windows-latest
            cachebase: C:/hostedtoolcache/windows
            vcarch: x64
            test: true
            examples: false
            doc: false
            testflags: "/J 1"
          - platform: msvc2017
            os: windows-latest
            cachebase: C:/hostedtoolcache/windows
            vcarch: x64_x86
            test: true
            examples: false
            doc: false
            testflags: "/J 1"
          - platform: winrt_x64_msvc2017
            os: windows-latest
            cachebase: C:/hostedtoolcache/windows
            vcarch: x64
            test: false
            examples: false
            doc: false
            testflags: "/J 1"
          - platform: winrt_x86_msvc2017
            os: windows-latest
            cachebase: C:/hostedtoolcache/windows
            vcarch: x64_x86
            test: false
            examples: false
            doc: false
            testflags: "/J 1"
          - platform: winrt_armv7_msvc2017
            os: windows-latest
            cachebase: C:/hostedtoolcache/windows
            vcarch: x64_arm
            test: false
            examples: false
            doc: false
            testflags: "/J 1"
          - platform: mingw73_64
            os: windows-latest
            cachebase: C:/hostedtoolcache/windows
            test: true
            examples: false
            doc: false
            testflags: "-j 1"
          - platform: mingw73_32
            os: windows-latest
            cachebase: C:/hostedtoolcache/windows
            test: true
            examples: false
            doc: false
            testflags: "-j 1"
          - platform: clang_64
            os: macos-latest
            cachebase: /Users/runner/hostedtoolcache
            test: true
            examples: false
            doc: false
            testflags: "-j 1"
          - platform: ios
            os: macos-latest
            cachebase: /Users/runner/hostedtoolcache
            test: false
            examples: false
            doc: false
            testflags: "-j 1"

    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: recursive
      - uses: actions/setup-python@v1
      - uses: mymindstorm/setup-emsdk@v1
        if: matrix.platform == 'wasm_32'
        with:
          version: sdk-1.38.27-64bit
      - uses: ilammy/msvc-dev-cmd@v1
        if: contains(matrix.platform, 'msvc')
        with:
          arch: ${{matrix.vcarch}}
          #toolset: 14.16
          uwp: ${{contains(matrix.platform, 'winrt')}}
      - uses: actions/cache@v1
        id: cache
        with:
          path: ${{matrix.cachebase}}/qt/${{matrix.version}}/${{matrix.platform}}
          key: qt-${{matrix.version}}-${{matrix.platform}}
      - uses: Skycoder42/action-setup-qt@master
        id: setup_qt
        with:
          version: ${{matrix.version}}
          platform: ${{matrix.platform}}
          install-args: --verbose
          cached: ${{matrix.cachebase}}/qt/${{matrix.version}}/${{matrix.platform}}
      - name: qmake
        run: |
          qmake CONFIG+=install_ok QT_PLATFORM=${{matrix.platform}}
          make qmake_all
      - name: make module
        run: |
          make
          make INSTALL_ROOT="${{steps.setup_qt.outputs.installdir}}" install
      - name: make tests
        run: |
          make all
          make ${{matrix.testflags}} run-tests
        if: matrix.test
      - name: make examples
        run: |
          make sub-examples
          cd examples && make INSTALL_ROOT="${{steps.setup_qt.outputs.installdir}}" install
        if: matrix.examples
      - name: make doc
        run: |
          make doxygen
          cd doc && make INSTALL_ROOT="${{steps.setup_qt.outputs.installdir}}" install
        if: matrix.doc
      - uses: actions/upload-artifact@v1
        with:
          name: qtjsonserializer-${{matrix.platform}}-${{matrix.version}}
          path: install_link

  build-no-converters:
    env:
      QDEP_CACHE_DIR: $HOME/.qdep-cache
    strategy:
      fail-fast: false
      matrix:
        version:
          - 5.13.2
        platform:
          - gcc_64
          - msvc2017_64
          - mingw73_64
          - clang_64

        include:
          - platform: gcc_64
            os: ubuntu-latest
            cachebase: /opt/hostedtoolcache
          - platform: msvc2017_64
            os: windows-latest
            cachebase: C:/hostedtoolcache/windows
          - platform: mingw73_64
            os: windows-latest
            cachebase: C:/hostedtoolcache/windows
          - platform: clang_64
            os: macos-latest
            cachebase: /Users/runner/hostedtoolcache

    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: recursive
      - uses: actions/setup-python@v1
      - uses: ilammy/msvc-dev-cmd@v1
        if: contains(matrix.platform, 'msvc')
        with:
          arch: x64
          #toolset: 14.16
      - uses: actions/cache@v1
        id: cache
        with:
          path: ${{matrix.cachebase}}/qt/${{matrix.version}}/${{matrix.platform}}
          key: qt-${{matrix.version}}-${{matrix.platform}}
      - uses: Skycoder42/action-setup-qt@master
        with:
          version: ${{matrix.version}}
          platform: ${{matrix.platform}}
          install-args: --verbose
      - name: qmake
        run: |
          qmake CONFIG+=no_register_json_converters QT_PLATFORM=${{matrix.platform}}
          make qmake_all
      - name: make module
        run: make
